=== scsoares/english-school-xml/englishSchools.dtd
<!ELEMENT englishSchools (englishSchool*)>
<!ATTLIST englishSchool id CDATA #REQUIRED>
<!ELEMENT englishSchool (students*, classes*, teachers*)>
<!ELEMENT students (student*)>
<!ELEMENT student (studentName, address, studentClass)>
<!ATTLIST student dni CDATA #REQUIRED>
<!ATTLIST student birth-date CDATA #REQUIRED>
<!ELEMENT studentName (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT studentClass (#PCDATA)>
<!ELEMENT classes (levelClass*)>
<!ELEMENT levelClass (#PCDATA)>
<!ATTLIST levelClass classroom CDATA #REQUIRED>
<!ELEMENT teachers (teacher*)>
<!ELEMENT teacher (teacherName, teacherEmail, levelTeacher)>
<!ATTLIST teacher dni CDATA #REQUIRED>
<!ELEMENT teacherName (#PCDATA)>
<!ELEMENT teacherEmail (#PCDATA)>
<!ELEMENT levelTeacher (#PCDATA)>

=== scsoares/english-school-xml/englishSchools.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE englishSchools SYSTEM "englishSchools.dtd">


<englishSchools>
    <englishSchool id="FR405">

        <students>
            <student dni="43568234Q" birth-date="1997-07-21">
                <studentName>Paulo Pérez</studentName>
                <address>Calle Doramas, 17</address>
                <studentClass>A1</studentClass>
            </student>
        </students>

        <classes>
            <levelClass classroom="01">A1</levelClass>
            <levelClass classroom="02">A2</levelClass>
            <levelClass classroom="03">B1</levelClass>
            <levelClass classroom="04">B2</levelClass>
            <levelClass classroom="05">C1</levelClass>
            <levelClass classroom="06">C2</levelClass>
        </classes>

        <teachers>
            <teacher dni="83398239G">
                <teacherName>Juán Galdós</teacherName>
                <teacherEmail>juangaldos@institutotiburcio.es</teacherEmail>
                <levelTeacher>B2</levelTeacher>
            </teacher>
        </teachers>

    </englishSchool>
</englishSchools>
